### ISSUE TITLE
Username or password not set. Go to the settings tab, and enter your login details.

### ISSUE THREAD

**Issue by Jamadoo** [alexandrosmagos/instagram_commenter_ui#1]
Yes, i did input my correct login details in the settings. Any idea why this could be happening?

![image](https://github.com/alexandrosmagos/instagram_commenter_ui/assets/79752368/623d1534-550d-49bb-926d-89752cb4c158)
![image](https://github.com/alexandrosmagos/instagram_commenter_ui/assets/79752368/1f14edee-9d72-406b-b6a5-a3fa4ddccab8)

**Comment by Xeo23** [comment]
same

**Comment by Dinu-byte** [comment]
Just insert you ig username and password, then stop the server, then restart the server and it should work.

**Comment by alexandrosmagos** [comment]
Sorry for the long overdue response.

When changing (instagram, pushover, discord webhook) credentials/settings, a restart is required for them to take effect.
I updated the status message when updating those settings, as well as the readme.
