### ISSUE TITLE
duplicating usernames

### ISSUE THREAD

**Issue by joao-tecnico-chad** [alexandrosmagos/instagram_commenter_ui#2]
Hey
The script is commenting the same name several times, i just want it to comment each name once in pairs
Can it do that?

**Comment by alexandrosmagos** [comment]
![image](https://github.com/alexandrosmagos/instagram_commenter_ui/assets/12672076/1dd80585-d046-496d-be94-2cc262d36332)

If you specified three usernames to tag for example, the script just randomly picks out three out of all selected. 
If there is only one or two usernames, and you specified 3 to tag, one one going to be repeated.

Hope this helps.

**Comment by joao-tecnico-chad** [comment]
Yeah but what im saying is. I put 300 usernames and want it to make pairs and spam the post, but each name can only be commented once, and whats happening is its doing the same username again in different pairs of usernames that were commented on the post

**Comment by alexandrosmagos** [comment]
I understand. If I have time later tonight or tommorow, I'll implement this feature.

**Comment by joao-tecnico-chad** [comment]
A 2024-04-19 18:27, Alexandros Magos escreveu:

> I understand. If I have time later tonight or tommorow, I'll implement 
> this feature.
> 
> --
> Reply to this email directly, view it on GitHub [1], or unsubscribe 
> [2].
> You are receiving this because you authored the thread.Message ID: 
> ***@***.***>

Thanks bro!

Links:
------
[1] 
https://github.com/alexandrosmagos/instagram_commenter_ui/issues/2#issuecomment-2066996403
[2]
