### ISSUE TITLE
Πιθανη βελτιωση ή ιδεα

### ISSUE THREAD

**Issue by vekioschristos** [alexandrosmagos/instagram_commenter_ui#4]
Καλησπερα και ευχαριστουμε για το bot! Απλως θα ηθελα να ρωτησω, μπορουμε να το κανουμε καπως να μηδενιζουν τα Comments Posted καθε φορα που αλλαζουμε το λινκ ή καθε φορα που θετουμε σε λειτουργια τον σερβερ;

**Comment by alexandrosmagos** [comment]
Θα προσθέσω ένα κουμπί δίπλα από το counter για να το μηδενίσει σύντομα

**Comment by vekioschristos** [comment]
> Θα προσθέσω ένα κουμπί δίπλα από το counter για να το μηδενίσει σύντομα

Ευχαριστω πολυ για την απαντηση!

**Comment by alexandrosmagos** [comment]
Done, check the `How to update` section of the readme
