### ISSUE TITLE
Proxies

### ISSUE THREAD

**Issue by vekioschristos** [alexandrosmagos/instagram_commenter_ui#6]
Hi there! Quick question, if the proxies tab will be completed, will the Instagram spam block issue be resolved?

**Comment by alexandrosmagos** [comment]
I don't have any intention of creating any more features for this, only maintaning it.
But none the less, to bypass the comment limit or block, you'd have to have multiple accounts and multible proxies, which if someone wanted this to win a giveaway, having multible accounts would defeat the purpose.
