### ISSUE TITLE
idk is not working

### ISSUE THREAD

**Issue by ADI-VT-png** [alexandrosmagos/instagram_commenter_ui#7]
![Screenshot 2024-07-16 221657](https://github.com/user-attachments/assets/ede19377-56df-4f72-8eb0-3d352fe2cbef)

this issue apperere  when i put http://127.0.0.1:3000 this on chrome and i press enter 
![Screenshot 2024-07-16 221824](https://github.com/user-attachments/assets/cb656d91-7ada-4a9e-a165-fbb5c741b016)

**Comment by alexandrosmagos** [comment]
In the readme file, check out the `Getting Started` > `Instalation` section, number 4.

Make sure to type a random string in the session_secret parameter, and it will solve your issue.
