### ISSUE TITLE
when I enter the username in the panel, this error appears in cmd

### ISSUE THREAD

**Issue by ADI-VT-png** [alexandrosmagos/instagram_commenter_ui#8]
when I enter the username in the panel, this error appears in cmd
![Screenshot 2024-07-19 224900](https://github.com/user-attachments/assets/47ab8697-56fb-4193-88f7-067e34924965)

**Comment by alexandrosmagos** [comment]
Please read the Getting Started section of the readme, and rename the `.env example` file to` .env` in the settings folder. Then start the app again, and it'll work.

**Comment by ADI-VT-png** [comment]
look, this is the .env file and what's in it was renamed .env already
same problem
![Screenshot 2024-07-21 154427](https://github.com/user-attachments/assets/fe53a26a-a9d7-4acb-84dc-da48054d66fc)
![Screenshot 2024-07-21 154442](https://github.com/user-attachments/assets/126d2fee-2cdd-49ea-a3d4-c447bda2cb62)

**Comment by alexandrosmagos** [comment]
Your windows folder options hides the default file extensions. Your `.env` file is actually `.env.txt`.

To enable it, press Start to open the start menu, and search for `folder options`
![image](https://github.com/user-attachments/assets/f1e9f62a-d1e7-42c1-99ce-4d1146181747)

Then in the view tab, select the `Show hidden files, folders, and drives`, and press `OK`.
![image](https://github.com/user-attachments/assets/ea2652f9-6d27-403e-8dbb-65890c390901)


After this start the app again, and it should be resolved.
